- name: Download Proxmox VE repository key
  ansible.builtin.get_url:
    url: http://download.proxmox.com/debian/proxmox-release-bookworm.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
    mode: "0644"

- name: Add proxmox VE repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    state: present

- name: Update repo
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Install proxmox VE kernel
  ansible.builtin.apt:
    name: proxmox-default-kernel
    state: present

- name: Reboot
  ansible.builtin.reboot:

- name: Remove enterprise apt list if present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Install proxmox ve packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - proxmox-ve
    - postfix
    - open-iscsi
    - chrony

- name: Remove debian kernel
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - linux-image-amd64
    - 'linux-image-6.1*'

- name: Remove os-prober package
  ansible.builtin.apt:
    name: os-prober
    state: absent

- name: Add user to PVE authentication
  ansible.builtin.command:
    cmd: "pveum user add {{ ansible_user }}@pam"
  args:
    creates: "/etc/pve/user.cfg"

- name: Add user to Administrators group
  ansible.builtin.command:
    cmd: "pveum aclmod / -user {{ ansible_user }}@pam -role Administrator"
